/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.aldrin.hrms.gui.panel;

import com.aldrin.hrms.dao.impl.DBConnection;
import com.aldrin.hrms.dao.impl.PaymentDAOImpl;
import com.aldrin.hrms.dao.impl.UserDAOImpl;
import static com.aldrin.hrms.gui.panel.JPanelSales.setUserId;
import com.aldrin.hrms.util.ComboBoxList;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.text.DecimalFormat;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JPanel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.swing.JRViewer;

/**
 *
 * @author Java Programming with Aldrin
 */
public class JPanelReports extends javax.swing.JPanel {

    private com.aldrin.hrms.gui.JFrameHRMS jFrameHRMS;
    private DecimalFormat df = new DecimalFormat("##,##0.00");
    private static Long userId;
    private static Long fromId;
    private static Long toId;

    private JPanel panel = new JPanel();
    private JasperPrint JPrint;
    private JRViewer jrviewer;


    public JPanelReports() {
        initComponents();
        comboBoxUser();
        ComboBoxList userId = (ComboBoxList) this.jComboBoxUser.getSelectedItem();
        comboBoxFromInvoice(userId.getId());
        comboBoxToInvoice(userId.getId());
        //table data

        BorderLayout layout = new BorderLayout();
        jDesktopPane1.setLayout(layout);
        BorderLayout layout1 = new BorderLayout();
        panel.setLayout(layout1);
        jDesktopPane1.add(panel, BorderLayout.CENTER);
        panel.setBounds(1, 2, 660, 500);
        jrviewer = new JRViewer(null);
        panel.add(jrviewer, BorderLayout.CENTER);
        jrviewer.setPreferredSize(new Dimension(600, 451));
        jrviewer.setAutoscrolls(true);
        showReport();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXTipOfTheDay1 = new org.jdesktop.swingx.JXTipOfTheDay();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxUser = new javax.swing.JComboBox<>();
        jPanel10 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxFrom = new javax.swing.JComboBox<>();
        jPanel11 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxTo = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel4.setPreferredSize(new java.awt.Dimension(940, 40));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));

        jLabel2.setText("Reports");
        jPanel4.add(jLabel2);

        jPanel2.add(jPanel4, java.awt.BorderLayout.NORTH);

        jPanel14.setLayout(new java.awt.BorderLayout());

        jPanel15.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel16.setPreferredSize(new java.awt.Dimension(748, 45));
        jPanel16.setLayout(new java.awt.BorderLayout());

        jPanel5.setPreferredSize(new java.awt.Dimension(400, 100));
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 10));
        jPanel16.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel6.setPreferredSize(new java.awt.Dimension(900, 72));
        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 2, 10));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel9);

        jLabel3.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("User");
        jLabel3.setPreferredSize(new java.awt.Dimension(40, 25));
        jPanel6.add(jLabel3);

        jComboBoxUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxUser.setPreferredSize(new java.awt.Dimension(180, 25));
        jComboBoxUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxUserActionPerformed(evt);
            }
        });
        jPanel6.add(jComboBoxUser);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel10);

        jLabel5.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("From Invoicec ID:");
        jLabel5.setPreferredSize(new java.awt.Dimension(120, 25));
        jPanel6.add(jLabel5);

        jComboBoxFrom.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jComboBoxFrom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxFrom.setPreferredSize(new java.awt.Dimension(180, 25));
        jComboBoxFrom.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxFromItemStateChanged(evt);
            }
        });
        jComboBoxFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFromActionPerformed(evt);
            }
        });
        jComboBoxFrom.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jComboBoxFromPropertyChange(evt);
            }
        });
        jPanel6.add(jComboBoxFrom);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel11);

        jLabel6.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("To Invoice ID:");
        jLabel6.setPreferredSize(new java.awt.Dimension(100, 25));
        jPanel6.add(jLabel6);

        jComboBoxTo.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jComboBoxTo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxTo.setPreferredSize(new java.awt.Dimension(180, 25));
        jComboBoxTo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxToItemStateChanged(evt);
            }
        });
        jComboBoxTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxToActionPerformed(evt);
            }
        });
        jComboBoxTo.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jComboBoxToPropertyChange(evt);
            }
        });
        jPanel6.add(jComboBoxTo);

        jPanel16.add(jPanel6, java.awt.BorderLayout.WEST);

        jPanel3.add(jPanel16, java.awt.BorderLayout.NORTH);

        jPanel7.setLayout(new java.awt.BorderLayout());

        jPanel17.setLayout(new java.awt.BorderLayout());
        jPanel17.add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel17, java.awt.BorderLayout.CENTER);

        jPanel18.setPreferredSize(new java.awt.Dimension(10, 413));

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 311, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel18, java.awt.BorderLayout.WEST);

        jPanel19.setPreferredSize(new java.awt.Dimension(10, 100));

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 311, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel19, java.awt.BorderLayout.EAST);

        jPanel3.add(jPanel7, java.awt.BorderLayout.CENTER);

        jPanel8.setPreferredSize(new java.awt.Dimension(1003, 60));
        jPanel8.setLayout(new java.awt.BorderLayout());

        jPanel12.setPreferredSize(new java.awt.Dimension(82, 60));

        jButton1.setIcon(new FlatSVGIcon("svg/print.svg",40,40));
        jButton1.setText("Print");
        jButton1.setMargin(new java.awt.Insets(2, 2, 3, 2));
        jButton1.setPreferredSize(new java.awt.Dimension(90, 45));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton1);

        jPanel8.add(jPanel12, java.awt.BorderLayout.CENTER);

        jPanel13.setPreferredSize(new java.awt.Dimension(10, 40));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel8.add(jPanel13, java.awt.BorderLayout.EAST);

        jPanel3.add(jPanel8, java.awt.BorderLayout.PAGE_END);

        jPanel15.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel14.add(jPanel15, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel14, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxUserActionPerformed
        try {
            ComboBoxList toId = (ComboBoxList) this.jComboBoxUser.getSelectedItem();
            setUserId(toId.getId());
            comboBoxFromInvoice(toId.getId());
            comboBoxToInvoice(toId.getId());
            showReport();

        } catch (Exception e) {

        }
    }//GEN-LAST:event_jComboBoxUserActionPerformed

    private void jComboBoxFromItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxFromItemStateChanged

    }//GEN-LAST:event_jComboBoxFromItemStateChanged

    private void jComboBoxFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFromActionPerformed
        try {
            ComboBoxList toId = (ComboBoxList) this.jComboBoxFrom.getSelectedItem();
            setFromId(toId.getId());
            showReport();
        } catch (Exception e) {

        }
    }//GEN-LAST:event_jComboBoxFromActionPerformed

    private void jComboBoxFromPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboBoxFromPropertyChange

    }//GEN-LAST:event_jComboBoxFromPropertyChange

    private void jComboBoxToItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxToItemStateChanged

    }//GEN-LAST:event_jComboBoxToItemStateChanged

    private void jComboBoxToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxToActionPerformed
        try {
            ComboBoxList toId = (ComboBoxList) this.jComboBoxTo.getSelectedItem();
            setToId(toId.getId());
            //            selectPaymentReceived();
            showReport();
        } catch (Exception e) {

        }
    }//GEN-LAST:event_jComboBoxToActionPerformed

    private void jComboBoxToPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboBoxToPropertyChange

    }//GEN-LAST:event_jComboBoxToPropertyChange

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        autoPrint();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<Object> jComboBoxFrom;
    private javax.swing.JComboBox<Object> jComboBoxTo;
    private javax.swing.JComboBox<Object> jComboBoxUser;
    private static javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private org.jdesktop.swingx.JXTipOfTheDay jXTipOfTheDay1;
    // End of variables declaration//GEN-END:variables
   private UserDAOImpl userDAOImpl = new UserDAOImpl();
    private PaymentDAOImpl paymentDAOImpl = new PaymentDAOImpl();

    private void comboBoxUser() {
        userDAOImpl.comboBoxUser();
        jComboBoxUser.removeAllItems();
        for (ComboBoxList a : userDAOImpl.getList()) {
            this.jComboBoxUser.addItem(a);
        }
    }

    private void comboBoxFromInvoice(Long userId) {
        paymentDAOImpl.comboBoxInvoiceIdByUserId(userId);
        jComboBoxFrom.removeAllItems();
        for (ComboBoxList a : paymentDAOImpl.getList()) {
            this.jComboBoxFrom.addItem(a);
        }
    }

    private void comboBoxToInvoice(Long userId) {
        paymentDAOImpl.comboBoxInvoiceIdByUserId(userId);
        jComboBoxTo.removeAllItems();
        for (ComboBoxList a : paymentDAOImpl.getList()) {
            this.jComboBoxTo.addItem(a);
        }
    }

    /**
     * @return the userId
     */
    public static Long getUserId() {
        return userId;
    }

    /**
     * @param aUserId the userId to set
     */
    public static void setUserId(Long aUserId) {
        userId = aUserId;
    }

    public static void showReport() {
        JasperPrint JPrint;
        try {
            DBConnection con = new DBConnection();
            con.getDBConn();
            String fullPath = System.getProperty("user.dir") + "/src/main/resources/reports/userSales.jasper";
            Map<String, Object> param = new HashMap<String, Object>();

            param.put("USERID", getUserId());
            param.put("FROMID", getFromId());
            param.put("TOID", getToId());
            JPrint = JasperFillManager.fillReport(fullPath, param, con.getCon());
            JRViewer jrv = new JRViewer(JPrint);
            jDesktopPane1.removeAll();
            jDesktopPane1.add(jrv);
            jDesktopPane1.revalidate();
        } catch (Exception ex) {
            System.out.println(ex.toString());
        }
    }

    public void autoPrint() {
        try {
            DBConnection con = new DBConnection();
            con.getDBConn();
            String fullPath = System.getProperty("user.dir") + "/src/main/resources/reports/userSales.jasper";
            Map<String, Object> param = new HashMap<String, Object>();
            param.put("USERID", 1L);
            param.put("FROMID", getFromId());
            param.put("TOID", getToId());
            JasperPrint jp = JasperFillManager.fillReport(fullPath, param, con.getCon());
            JasperPrintManager.printReport(jp, false); // print to default printer

//            JasperExportManager.exportReportToPdfFile(jp, "C:\\Users\\admin\\Desktop\\userSales.pdf");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * @return the fromId
     */
    public static Long getFromId() {
        return fromId;
    }

    /**
     * @param aFromId the fromId to set
     */
    public static void setFromId(Long aFromId) {
        fromId = aFromId;
    }

    /**
     * @return the toId
     */
    public static Long getToId() {
        return toId;
    }

    /**
     * @param aToId the toId to set
     */
    public static void setToId(Long aToId) {
        toId = aToId;
    }

}
