/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.aldrin.hrms.gui.dialog.au;

import com.aldrin.hrms.dao.impl.RoomTypeDAOImpl;
import com.aldrin.hrms.gui.JFrameHRMS;
import com.aldrin.hrms.model.RoomType;
import com.aldrin.hrms.util.NumberInput;
import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.io.File;
import javax.swing.JOptionPane;

/**
 *
 * @author ALDRIN B. C.
 */
public class JDialogRoomTypeAU extends javax.swing.JDialog {

    /**
     * Creates new form JDialogRoomTypeAU
     */
    private JFrameHRMS jFrameHRMS;
    private RoomType roomType = new RoomType();
    static String title;
    private RoomTypeDAOImpl roomTypeDAOImpl = new RoomTypeDAOImpl();

    public JDialogRoomTypeAU(JFrameHRMS jFrameHRMS, boolean modal) {
        super(jFrameHRMS, modal);
        initComponents();
        setTitle("Add");
        this.title = "Add";
        jButton1.setIcon(new FlatSVGIcon("svg/save.svg", 24, 24));
        jTextFieldType.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "TYPE");
        jTextFieldCapacity.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "CAPACITY");
        jTextFieldDescription.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "DESCRIPTION");
        new NumberInput().intValidator(jTextFieldCapacity);
    }

    public JDialogRoomTypeAU(JFrameHRMS jFrameCafSys, boolean modal, RoomType roomType, String title) {
        super(jFrameCafSys, modal);
        initComponents();
        setTitle(title);
        this.title = title;
        this.roomType = roomType;
        jButton1.setIcon(new FlatSVGIcon("svg/edit.svg", 24, 24));
        jButton1.setText(title);
        jTextFieldType.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "TYPE");
        jTextFieldCapacity.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "CAPACITY");
        jTextFieldDescription.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "DESCRIPTION");
        jTextFieldType.setText(roomType.getType());
        jTextFieldCapacity.setText(String.valueOf(roomType.getCapacity()));
        jTextFieldDescription.setText(roomType.getDescription());
        new NumberInput().intValidator(jTextFieldCapacity);
    }

    public JDialogRoomTypeAU(JFrameHRMS jFrameHRMS, boolean modal, String title, RoomType roomType) {
        super(jFrameHRMS, modal);
        initComponents();
        setTitle(title);
        this.roomType = roomType;
        this.title = title;
        jButton1.setIcon(new FlatSVGIcon("svg/delete.svg", 24, 24));
        jButton1.setText(title);
        jTextFieldType.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "TYPE");
        jTextFieldCapacity.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "0");
        jTextFieldDescription.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "DESCRIPTION");
        jTextFieldType.setText(roomType.getType());
        jTextFieldCapacity.setText(String.valueOf(roomType.getCapacity()));
        jTextFieldDescription.setText(roomType.getDescription());
        new NumberInput().intValidator(jTextFieldCapacity);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldCapacity = new javax.swing.JTextField();
        jTextFieldType = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldDescription = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("TYPE:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 20, 80, 30));
        getContentPane().add(jTextFieldCapacity, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 250, 30));
        getContentPane().add(jTextFieldType, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 250, 30));

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 140, 30));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("CAPACITY:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 70, 80, 30));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("DESCRIPTION:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 120, 80, 30));
        getContentPane().add(jTextFieldDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 250, 30));

        setSize(new java.awt.Dimension(373, 291));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (this.title.equals("Add")) {
            int response = JOptionPane.showConfirmDialog(jFrameHRMS, "Are you sure to save " + jTextFieldType.getText() + " ?", "Save confirmation", JOptionPane.YES_NO_OPTION);
            if (response == JOptionPane.YES_OPTION) {
                this.roomType.setId(null);
                this.roomType.setType(jTextFieldType.getText());
                this.roomType.setCapacity(Integer.parseInt(jTextFieldCapacity.getText()));
                this.roomType.setDescription(jTextFieldDescription.getText());
                roomTypeDAOImpl.addRoomType(roomType);
                this.dispose();
            }
        } else if (this.title.equals("Update")) {
            int response = JOptionPane.showConfirmDialog(jFrameHRMS, "Are you sure to update " + jTextFieldType.getText() + " ?", "Save confirmation", JOptionPane.YES_NO_OPTION);
            if (response == JOptionPane.YES_OPTION) {
                this.roomType.setType(jTextFieldType.getText());
                this.roomType.setCapacity(Integer.parseInt(jTextFieldCapacity.getText()));
                this.roomType.setDescription(jTextFieldDescription.getText());
                roomTypeDAOImpl.updateRoomType(roomType);
                this.dispose();
            }
        } else if (this.title.equals("Delete")) {
            int response = JOptionPane.showConfirmDialog(jFrameHRMS, "Are you sure to delete " + jTextFieldType.getText() + " ?", "Save confirmation", JOptionPane.YES_NO_OPTION);
            if (response == JOptionPane.YES_OPTION) {
                roomTypeDAOImpl.deleteRoomType(roomType);
                this.dispose();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextFieldCapacity;
    private javax.swing.JTextField jTextFieldDescription;
    private javax.swing.JTextField jTextFieldType;
    // End of variables declaration//GEN-END:variables
    private File pictureFile = null;

}
